ManagingGroup.create({label: "loan", name: "Fjärrinlån", email: "n/n", sublocation: "440099", is_active: true, position: 10})
ManagingGroup.create({label: "copies", name: "Kopior och kapitel", email: "n/n", sublocation: "400099", is_active: true, position: 20})
ManagingGroup.create({label: "microfilm", name: "Mikrofilm", email: "n/n", sublocation: "420099", is_active: true, position: 30})
ManagingGroup.create({label: "score", name: "Musiktryck", email: "n/n", sublocation: "620099", is_active: true, position: 40})

ManagingGroup.create({label: "Gumu-acquisitions", name: "Biblioteket för musik och dramatik, inköp", email: "n/n", sublocation: nil, is_active: true, position: 50})
ManagingGroup.create({label: "Gm-acquisitions", name: "Biomedicinska biblioteket, inköp", email: "n/n", sublocation: nil, position: 60})
ManagingGroup.create({label: "Ge-acquisitions", name: "Ekonomiska biblioteket, inköp", email: "n/n", sublocation: nil, is_active: true, position: 70})
ManagingGroup.create({label: "G-acquisitions", name: "Humanistiska biblioteket, inköp", email: "n/n", sublocation: nil, is_active: true, position: 80})
ManagingGroup.create({label: "G-legal-deposits", name: "Humanistiska biblioteket, pliktleverans", email: "n/n", sublocation: nil, is_active: true, position: 90})
ManagingGroup.create({label: "Ghdk-acquisitions", name: "Konstbiblioteket, inköp", email: "n/n", sublocation: nil, is_active: true, position: 100})
ManagingGroup.create({label: "Gp-acquisitions", name: "Pedagogiska biblioteket, inköp", email: "n/n", sublocation: nil, is_active: true, position: 110})
ManagingGroup.create({label: "Gk-acquisitions", name: "Samhällsvetenskapliga biblioteket, inköp", email: "n/n", sublocation: nil, is_active: true, position: 120})
