OrderType.create({id: 1, name_sv: "Artikelkopia", name_en: "Copy of article", label: "photocopy", auth_required: false})
OrderType.create({id: 2, name_sv: "Bok", name_en: "Book", label: "loan", auth_required: true})
OrderType.create({id: 3, name_sv: "Kopia av bokkapitel", name_en: "Copy of book Chapter", label: "photocopy_chapter", auth_required: false})
OrderType.create({id: 4, name_sv: "Musiktryck", name_en: "Score", label: "score", auth_required: true})
OrderType.create({id: 5, name_sv: "Mikrofilmad dagstidning", name_en: "Microfilm newspaper", label: "microfilm", auth_required: false})
