PickupLocation.create({id: 1, label: "G", name_sv: "Humanistiska biblioteket", name_en: "Humanities Library", email: "gubgfj@ub.gu.se", is_sigel: TRUE, sigel: "G"})
PickupLocation.create({id: 2, label: "G-plikt", name_sv: "Humanistiska biblioteket, pliktleverans", name_en: "Humanities Library Legal Deposits", email: "plikt@ub.gu.se", is_sigel: FALSE, sigel: "G"})
PickupLocation.create({id: 3, label: "G-inkop", name_sv: "Humanistiska biblioteket, inköp", name_en: "Humanities Library, Acquisitions", email: "ubinkopg@ub.gu.se", is_sigel: FALSE, sigel: "G"})
PickupLocation.create({id: 4, label: "Ge", name_sv: "Ekonomiska biblioteket", name_en: "Economics Library", email: "Ge.Interurb@ub.gu.se", is_sigel: TRUE, sigel: "Ge"})
PickupLocation.create({id: 5, label: "Ge-inkop", name_sv: "Ekonomiska biblioteket, inköp", name_en: "Economics Library, Acquisitions", email: "gemedier@ub.gu.se", is_sigel: FALSE, sigel: "Ge"})
PickupLocation.create({id: 6, label: "Gg", name_sv: "Geovetenskapliga biblioteket med kulturvård", name_en: "Earth Sciences and Conservation Library, Acquisitions", email: "geovet.bibl@ub.gu.se", is_sigel: TRUE, sigel: "Gg"})
PickupLocation.create({id: 7, label: "Gm", name_sv: "Biomedicinska biblioteket", name_en: "Biomedical Library", email: "gubgmlan@ub.gu.se", is_sigel: TRUE, sigel: "Gm"})
PickupLocation.create({id: 8, label: "Gm-inkop", name_sv: "Biomedicinska biblioteket, inköp", name_en: "Biomedical Library, Acquisitions", email: "gm.forv@ub.gu.se", is_sigel: FALSE, sigel: "Gm"})
PickupLocation.create({id: 9, label: "Gp", name_sv: "Pedagogiska biblioteket", name_en: "Education Library", email: "gpfjarr@ub.gu.se", is_sigel: TRUE, sigel: "Gp"})
PickupLocation.create({id: 19, label: "Gg-inkop", name_sv: "Geovetenskapliga biblioteket med kulturvård, inköp", name_en: "Earth Sciences and Conservation Library, Acquisitions", email: "gm.forv@ub.gu.se", is_sigel: FALSE, sigel: "Gg"})
PickupLocation.create({id: 20, label: "Gp-inkop", name_sv: "Pedagogiska biblioteket, inköp", name_en: "Education Library, Acquisitions", email: "gpmedier@ub.gu.se", is_sigel: FALSE, sigel: "Gp"})
PickupLocation.create({id: 21, label: "Gk", name_sv: "Samhällsvetenskapliga biblioteket", name_en: "Social Sciences Library", email: "gubgklan@ub.gu.se", is_sigel: TRUE, sigel: "Gk"})
PickupLocation.create({id: 22, label: "Gk-inkop", name_sv: "Samhällsvetenskapliga biblioteket, inköp", name_en: "Social Sciences Library, Acquisitions", email: "sam.inkop@ub.gu.se", is_sigel: FALSE, sigel: "Gk"})
PickupLocation.create({id: 23, label: "Gcl", name_sv: "Campus Linné", name_en: "Learning Centre Campus Linné", email: "ubexp-l2@ub.gu.se", is_sigel: TRUE, sigel: "Gcl"})
PickupLocation.create({id: 24, label: "Ghdk", name_sv: "Konstbiblioteket", name_en: "Art Library", email: "ubghdk@ub.gu.se", is_sigel: TRUE, sigel: "Ghdk"})
PickupLocation.create({id: 25, label: "Ghdk-inkop", name_sv: "Konstbiblioteket, inköp", name_en: "Art Library, Acquisitions", email: "ubghdk@ub.gu.se", is_sigel: FALSE, sigel: "Ghdk"})
PickupLocation.create({id: 26, label: "Gumu", name_sv: "Biblioteket för musik och dramatik", name_en: "Music and Drama Library", email: "gumu.lan@ub.gu.se", is_sigel: TRUE, sigel: "Gumu"})
PickupLocation.create({id: 27, label: "Gumu-inkop", name_sv: "Biblioteket för musik och dramatik, inköp", name_en: "Music and Drama Library, Acquisitions", email: "gumu.lan@ub.gu.se", is_sigel: FALSE, sigel: "Gumu"})
