StatusGroup.create({id: 1, name_sv: "Alla statusar", name_en: "All statuses", label: "all", position: 0})
StatusGroup.create({id: 2, name_sv: "Ny", name_en: "New", label: "new", position: 10})
StatusGroup.create({id: 3, name_sv: "Beställd", name_en: "Requested", label: "requested", position: 20})
StatusGroup.create({id: 4, name_sv: "Mottagen", name_en: "Received", label: "received", position: 70})
StatusGroup.create({id: 5, name_sv: "Returnerad", name_en: "Returned", label: "returned", position: 100})
StatusGroup.create({id: 7, name_sv: "Levererad", name_en: "Delivered", label: "delivered", position: 90})
StatusGroup.create({id: 8, name_sv: "Väntar på svar", name_en: "Awaiting answer", label: "awaiting_answer", position: 50})
StatusGroup.create({id: 9, name_sv: "Negativt svar", name_en: "Negative response", label: "negative_response", position: 60})
StatusGroup.create({id: 10, name_sv: "Makulerad", name_en: "Cancelled", label: "cancelled", position: 110})
StatusGroup.create({id: 12, name_sv: "Under arbete", name_en: "In progress", label: "in_progress", position: 40})
