Status.create({id: 1, name_sv: "Ny", name_en: "New",label: "new", is_active: TRUE, position: 10})
Status.create({id: 2, name_sv: "Beställd", name_en: "Requested",label: "requested", is_active: TRUE, position: 30})
Status.create({id: 3, name_sv: "Mottagen", name_en: "Received",label: "received", is_active: TRUE, position: 90})
Status.create({id: 4, name_sv: "Returnerad", name_en: "Returned",label: "returned", is_active: TRUE, position: 120})
Status.create({id: 5, name_sv: "Ur egen samling", name_en: "From local collection",label: "from_local_collection", is_active: FALSE, position: nil})
Status.create({id: 6, name_sv: "Utskriven", name_en: "Printed",label: "printed", is_active: FALSE, position: nil})
Status.create({id: 7, name_sv: "Levererad", name_en: "Delivered",label: "delivered", is_active: TRUE, position: 110})
Status.create({id: 8, name_sv: "Väntar på svar", name_en: "Awaiting answer",label: "awaiting_answer", is_active: TRUE, position: 60})
Status.create({id: 9, name_sv: "Negativt svar", name_en: "Negative response",label: "negative_response", is_active: FALSE, position: nil})
Status.create({id: 10, name_sv: "Makulerad", name_en: "Cancelled",label: "cancelled", is_active: TRUE, position: 130})
Status.create({id: 11, name_sv: "Negativt svar (Libris)", name_en: "Negative Response (Libris)",label: "negative_response_libris", is_active: TRUE, position: 80})
Status.create({id: 12, name_sv: "Ny (Libris låntagarbeställning)", name_en: "New (Libris Enduser request)",label: "new_libris_enduser_request", is_active: FALSE, position: nil})
Status.create({id: 13, name_sv: "Arkiverad", name_en: "Archived",label: "archived", is_active: FALSE, position: nil})
Status.create({id: 14, name_sv: "Under arbete", name_en: "In progress",label: "in_progress", is_active: TRUE, position: 50})
Status.create({id: 15, name_sv: "Till fakturering", name_en: "To billing",label: "to_billing", is_active: FALSE, position: nil})
