secret_access_token: <%= ENV["ILL_SECRET_ACCESS_TOKEN"] %>
koha:
  base_url: <%= ENV["ILL_KOHA_SVC_URL"] %>
  user: <%= ENV["ILL_KOHA_USER"] %>
  password: <%= ENV["ILL_KOHA_PASSWORD"] %>
oauth2:
  provider: <%= ENV["GUB_OAUTH2_PROVIDER"] %>
  client_id: <%= ENV["GUB_OAUTH2_CLIENT_ID"] %>
  client_secret: <%= ENV["GUB_OAUTH2_CLIENT_SECRET"] %>
  token_endpoint: <%= ENV["GUB_OAUTH2_TOKEN_ENDPOINT"] %>
  user_endpoint: <%= ENV["GUB_OAUTH2_USER_ENDPOINT"] %>
